### ISSUE TITLE
theme request

### ISSUE THREAD

**Issue by sahilguleri** [linuxmint/cinnamon-themes#17]
plz someone make a theme 
1. whenever wireless connection is low wireless icon show a yellow star over it (or something like that) . like in windows
2. application icons in menu zoom in on mouse over

**Comment by JosephMcc** [comment]
This isn't really the place for those requests, as they are outside of what's possible in the cinnamon theme. The menu zoom is probably more suitable to the Cinnamon repo and the other is an icon feature request. Not something that's likely to change though.
