### ISSUE TITLE
Mint-X-Aqua Color missing in Firefox's notification bar

### ISSUE THREAD

**Issue by brouillon** [linuxmint/cinnamon-themes#48]
Hello,

I use Linux Mint 18.1 with Cinnamon 3.2.7 with Mint-X-Aqua.

In Firefox and for example noscript, there is a notification zone in the bottom of the browser window, this notification was green !

Is there something to do in cinnamon theme ? the green color let me think it comes from mint !

![selection_001](https://cloud.githubusercontent.com/assets/2931266/22247875/50e14798-e23c-11e6-81de-b553089d3806.png)

**Comment by JosephMcc** [comment]
This has nothing to do with the Cinnamon theme. It's controlled by the gtk theme.

**Comment by brouillon** [comment]
So in theme setting, if I use : 
window border : Mint-X
control : Mint-X-Aqua
Desktop : Linux Mint

In this list who is the gtk theme ? Is it Mint-X parent of Mint-X-Aqua ?
Can you please help me to find this notification color, and to change it ?

**Comment by brouillon** [comment]
I found it in :
```
/usr/share/themes/Mint-X-Aqua/gtk-3.0/gtk-main-common.css
```
Then replace :
```
/*@define-color info_color #9ab87c;*/
@define-color info_color #6cabcd;
```
This file is not in this repo, so where does it come ? and how to fix this for everyone using Mint-X-Aqua ?

Sorry for my misunderstood of gtk theming, and my bad english

**Comment by JosephMcc** [comment]
> Sorry for my misunderstood of gtk theming, and my bad english

Not a problem. It comes from the mint-themes-gtk3 repo. I don't really want to change it though. The different types of info bars use the same colors throughout the different color variations of the theme.
